### ISSUE TITLE
PGO initialization fails on MariaDB download

### ISSUE THREAD

**Issue by cmb69** [OSTC/php-sdk-binary-tools#69]
When `phpsdk_pgo --init` attempts to download the MariaDB archive, it fails. Relevant output when `CURLOPT_VERBOSE` is enabled:
````
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Failed sending HTTP request
````
I have not been able to reproduce this failure with a small standalone script. Some global state might not be properly reset; perhaps a bug in PHP?

**Comment by weltling** [comment]
If curl is involved, it might be the issue. AFAIR there was recently some issues with HTTP2 which was fixed in 7.69.1.

Thanks.

**Comment by cmb69** [comment]
Thanks! I've just checked with PHP 7.4.5RC1 which has libcurl 7.69.1, but the download still fails.

**Comment by dalehhirt** [comment]
Closing as fixed.
